#!/usr/bin/zsh

function check_user {
    local ROOT_UID=0

    if [ "$UID" -eq "$ROOT_UID" ]
    then
        echo "You must not be root"
        exit 0
    fi
}

function check_directory {
    local current_directory=$(pwd)

    if [ "$current_directory" != "$HOME/Conf" ]
    then
        cd $HOME/Conf
    fi
}

function build_command-t() {
    cd $HOME/.vim/ruby/command-t
    ruby extconf.rb
    echo "Build command-t plugin"
    make
    cd $HOME/Conf
}

function set_vim_conf() {
    check_directory
    echo "Delete the actualy .vim directory"
    rm -rf $HOME/.vim

    echo "Copy .vimrc from git repository"
    cp vimrc $HOME/.vimrc

    echo "Copy .vim directory from git repository"
    cp -r vim $HOME/.vim
    build_command-t
}

function set_system_config() {
    check_directory
    cp xmodmaprc $HOME/.xmodmaprc
    cp xinitrc $HOME/.xinitrc
    cp Xdefaults $HOME/.Xdefaults
}

check_user
set_vim_conf
set_system_config

echo "The script has $SECONDS secondes to run"
