#!/usr/bin/zsh

function check_directory {
    local current_directory=$(pwd)

    if [ current_directory != $HOME/Conf ]
    then
        cd $HOME/Conf
    fi
}

function build_command-t() {
    cd $HOME/.vim/ruby/command-t
    ruby extconf.rb
    echo "Build command-t plugin"
    make
    cd $HOME/Conf
}

function set_vim_conf() {
    echo "Delete the actualy .vim directory"
    rm -rf $HOME/.vim

    echo "Copy .vimrc from git repository"
    cp vimrc $HOME/.vimrc

    echo "Copy .vim directory from git repository"
    cp -r vim $HOME/.vim
    build_command-t
}

function set_system_config() {
    cp xmodmaprc $HOME/.xmodmaprc
    cp xinitrc $HOME/.xinitrc
    cp Xdefaults $HOME/.Xdefaults
}

set_vim_conf
set_system_config
