#!/usr/bin/zsh

function update_wmfs {
    cd $HOME/wmfs
    git pull
    make install
    wmfs -c reload
    cd
}

function new_install_wmfs {
    cd $HOME
    rm -rf $HOME/wmfs
    git clone https://github.com/xorg62/wmfs.git
    cd wmfs
    ./configure
    make
    sudo make install
    cd
}

new_install_wmfs
