#!/usr/bin/zsh

function update_wmfs {
    cd $HOME/wmfs
    git pull
    sudo make install
    wmfs -c reload
    cd
}

function new_install_wmfs {
    cd $HOME
    if [ -e "$HOME/wmfs" ]
    then
        rm -rf $HOME/wmfs
    fi
    git clone https://github.com/xorg62/wmfs.git
    cd wmfs
    ./configure
    make
    sudo make install
    cd
}

if [ "$1" = 'update' ]
then
    update_wmfs
else
    new_install_wmfs
fi
